name: Bending
description: Bending plugin for PaperMC.
author: Moros
version: ${pluginVersion}
main: me.moros.bending.Bending
softdepend: [PlaceholderAPI, WorldGuard, GriefPrevention, Towny, LWC]
api-version: 1.16
commands:
  bending:
    description: Interact with the bending plugin
    default: true
    aliases: [bending,bend,b,avatar,atla,tla]
  preset:
    description: Manage bending presets
    default: true
    aliases: [presets,preset,pr,p]
  modify:
      description: Manage bending attribute modifiers
      default: op
      aliases: [bmodify,bmod,bm,modify,mod]
permissions:
  bending.admin:
    description: Grants access to all commands and abilities.
    default: op
    children:
      bending.player: true
      bending.bluefire: true
      bending.command.reload: true
      bending.command.add: true
      bending.command.remove: true
      bending.command.choose.other: true
      bending.command.add.other: true
      bending.command.remove.other: true
      bending.command.modify: true
      bending.command.modify.other: true
  bending.player:
    default: true
    children:
      bending.command.bind: true
      bending.command.choose: true
      bending.command.display: true
      bending.command.help: true
      bending.command.preset: true
      bending.command.toggle: true
      bending.command.board: true
      bending.command.version: true
      bending.air: true
      bending.chi: true
      bending.earth: true
      bending.fire: true
      bending.water: true
  bending.air:
    children:
      bending.command.choose.Air: true
      bending.ability.AirAgility: true
      bending.ability.GracefulDescent: true
      bending.ability.AirWheel: true
      bending.ability.AirBlade: true
      bending.ability.AirBlast: true
      bending.ability.AirBreath: true
      bending.ability.AirBurst: true
      bending.ability.AirPunch: true
      bending.ability.AirScooter: true
      bending.ability.AirShield: true
      bending.ability.AirSpout: true
      bending.ability.AirSwipe: true
      bending.ability.Tornado: true
  bending.earth:
    children:
      bending.metal: true
      bending.lava: true
      bending.command.choose.Earth: true
      bending.ability.DensityShift: true
      bending.ability.EarthCling: true
      bending.ability.FerroControl: true
      bending.ability.Bulwark: true
      bending.ability.Catapult: true
      bending.ability.Collapse: true
      bending.ability.EarthArmor: true
      bending.ability.EarthBlast: true
      bending.ability.EarthGlove: true
      bending.ability.EarthLine: true
      bending.ability.EarthShot: true
      bending.ability.EarthSmash: true
      bending.ability.EarthTunnel: true
      bending.ability.LavaDisk: true
      bending.ability.MetalCable: true
      bending.ability.RaiseEarth: true
      bending.ability.Shockwave: true
  bending.fire:
    children:
      bending.command.choose.Fire: true
      bending.ability.FireKick: true
      bending.ability.FireSpin: true
      bending.ability.FireWheel: true
      bending.ability.Blaze: true
      bending.ability.Combustion: true
      bending.ability.FireBall: true
      bending.ability.FireBlast: true
      bending.ability.FireBreath: true
      bending.ability.FireBurst: true
      bending.ability.FireJet: true
      bending.ability.FireShield: true
      bending.ability.FireWall: true
      bending.ability.FlameRush: true
      bending.ability.HeatControl: true
      bending.ability.Lightning: true
  bending.water:
    children:
      bending.command.choose.Water: true
      bending.ability.FastSwim: true
      bending.ability.Hydrosink: true
      bending.ability.Iceberg: true
      bending.ability.WaterGimbal: true
      bending.ability.FrostBreath: true
      bending.ability.HealingWaters: true
      bending.ability.IceCrawl: true
      bending.ability.IceSpike: true
      bending.ability.IceWall: true
      bending.ability.OctopusForm: true
      bending.ability.PhaseChange: true
      bending.ability.Torrent: true
      bending.ability.WaterBubble: true
      bending.ability.WaterManipulation: true
      bending.ability.WaterRing: true
      bending.ability.WaterSpout: true
      bending.ability.WaterWave: true
